#!/usr/bin/env python3
"""
シナリオラボ v16 パッチスクリプト
- アノテーション機能の大幅強化（展開可能なインラインコメントパネル）
- 行単位でBefore/After改稿例を展開表示
- 評価エンジン精密化（脚本固有のテキストを動的に引用）
- ローディングエラー対策（CSS定義の追加・構文保護）
- エンジンバナーをv16に更新
"""

import re, sys

TARGET = 'public/static/app.js'

with open(TARGET, 'r', encoding='utf-8') as f:
    src = f.read()

orig_len = len(src)
patches_applied = []

# ════════════════════════════════════════════════════════════════
# PATCH 1: エンジンバナーをv16に更新
# ════════════════════════════════════════════════════════════════
old1 = '//  シナリオラボ 職員室 — 精密採点エンジン v15.0'
new1 = '//  シナリオラボ 職員室 — 精密採点エンジン v16.0'
if old1 in src:
    src = src.replace(old1, new1, 1)
    patches_applied.append('1) Engine banner v15→v16')
else:
    patches_applied.append('1) SKIP: Engine banner not found')

# ════════════════════════════════════════════════════════════════
# PATCH 2: エクスポートフッターのバージョンをv16に更新
# ════════════════════════════════════════════════════════════════
old2 = 'Generated by シナリオラボ 職員室 自動採点システム v13'
new2 = 'Generated by シナリオラボ 職員室 自動採点システム v16'
if old2 in src:
    src = src.replace(old2, new2, 1)
    patches_applied.append('2) Export footer v13→v16')
else:
    patches_applied.append('2) SKIP: Export footer not found')

# ════════════════════════════════════════════════════════════════
# PATCH 3: アノテーション HTML生成を大幅強化
# 展開可能な詳細コメントパネルを各行に追加
# badgeHtml + detailPanel の2層構造
# ════════════════════════════════════════════════════════════════
old3 = '''    // Build badge HTML
    let badgeHtml = '';
    if (annotMap[ri] && annotMap[ri].length > 0) {
      annotCount += annotMap[ri].length;
      annotMap[ri].forEach(ann => {
        const badgeType = ann.type === 'bad' ? 'bad' : ann.type === 'good' ? 'good' : ann.type === 'warn' ? 'warn' : 'info';
        const icon = ann.type === 'bad' ? 'fa-triangle-exclamation' : ann.type === 'good' ? 'fa-check' : ann.type === 'warn' ? 'fa-exclamation' : 'fa-circle-info';
        const tooltipId = 'ann-tt-' + ri + '-' + Math.random().toString(36).slice(2,6);
        // Build rich tooltip: label + full comment
        const tooltipText = ann.label + ': ' + ann.comment.replace(/\\n/g,' | ').slice(0,160);
        badgeHtml += '<span class="sr-ann-badge ' + badgeType + '" title="' + esc(tooltipText) + '" style="cursor:help">' +
          '<i class="fas ' + icon + '" style="font-size:7px"></i>' +
          esc(ann.label.slice(0,18)) + '</span>';
      });
    }

    annotHtml += '<div class="sr-ann-line2">' +
      '<span class="sr-ann-lnum2">' + (ri+1) + '</span>' +
      '<span class="sr-ann-text2 ' + lineClass + '">' + lineContent + '</span>' +
      (badgeHtml ? '<div class="sr-ann-badges">' + badgeHtml + '</div>' : '') +
      '</div>';
    prevLineB = l;
  });'''

new3 = '''    // ── v16: Build badge + expandable detail panel ────────────────
    let badgeHtml = '';
    let detailPanelHtml = '';
    const lineId = 'ann-line-' + ri;

    if (annotMap[ri] && annotMap[ri].length > 0) {
      annotCount += annotMap[ri].length;
      const hasBad = annotMap[ri].some(a => a.type === 'bad');
      const hasWarn = annotMap[ri].some(a => a.type === 'warn');
      const hasGood = annotMap[ri].some(a => a.type === 'good');

      // Badge strip
      annotMap[ri].forEach((ann, ai) => {
        const badgeType = ann.type === 'bad' ? 'bad' : ann.type === 'good' ? 'good' : ann.type === 'warn' ? 'warn' : 'info';
        const icon = ann.type === 'bad' ? 'fa-triangle-exclamation' : ann.type === 'good' ? 'fa-check' : ann.type === 'warn' ? 'fa-exclamation' : 'fa-circle-info';
        const panelId = 'ann-panel-' + ri + '-' + ai;
        const shortLabel = esc(ann.label.slice(0, 18));
        badgeHtml += '<span class="sr-ann-badge ' + badgeType + '" ' +
          'onclick="event.stopPropagation();const p=document.getElementById(\'' + panelId + '\');if(p){p.style.display=p.style.display===\'none\'?\'block\':\'none\';}" ' +
          'style="cursor:pointer" title="クリックで詳細を展開">' +
          '<i class="fas ' + icon + '" style="font-size:7px"></i>' + shortLabel + '</span>';

        // Detail panel for each annotation
        const bgColor = ann.type === 'bad' ? '#fff5f5' : ann.type === 'good' ? '#f0fdf4' : ann.type === 'warn' ? '#fffbeb' : '#eff6ff';
        const borderColor = ann.type === 'bad' ? '#fca5a5' : ann.type === 'good' ? '#86efac' : ann.type === 'warn' ? '#fde68a' : '#bfdbfe';
        const headerColor = ann.type === 'bad' ? '#dc2626' : ann.type === 'good' ? '#16a34a' : ann.type === 'warn' ? '#d97706' : '#2563eb';

        // Parse comment for Before/After sections
        const rawComment = ann.comment || '';
        const lines_c = rawComment.split('\\n');
        let beforeText = '';
        let afterText = '';
        let mainText = '';
        let inBefore = false, inAfter = false;
        lines_c.forEach(cl => {
          if (/^Before[:：]|^改稿前[:：]/.test(cl)) { inBefore = true; inAfter = false; beforeText += cl + '\\n'; }
          else if (/^After[:：]|^After[①②③][:：]|^改稿後[:：]|^After例[:：]/.test(cl)) { inAfter = true; inBefore = false; afterText += cl + '\\n'; }
          else if (inBefore) { beforeText += cl + '\\n'; }
          else if (inAfter) { afterText += cl + '\\n'; }
          else { inBefore = false; inAfter = false; mainText += cl + '\\n'; }
        });
        mainText = mainText.trim();
        beforeText = beforeText.trim();
        afterText = afterText.trim();

        let panelContent = '';
        if (mainText) {
          panelContent += '<div style="font-size:11px;color:#374151;line-height:1.75;margin-bottom:' + (beforeText||afterText?'8px':'0') + '">' + esc(mainText).replace(/\\n/g,'<br>') + '</div>';
        }
        if (beforeText || afterText) {
          panelContent += '<div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:4px">';
          if (beforeText) {
            panelContent += '<div style="background:#fef2f2;border:1px solid #fecaca;border-radius:6px;padding:6px 8px">' +
              '<div style="font-size:9px;font-weight:700;color:#dc2626;margin-bottom:3px"><i class="fas fa-times-circle" style="font-size:8px;margin-right:3px"></i>改稿前</div>' +
              '<pre style="font-size:10.5px;color:#7f1d1d;white-space:pre-wrap;margin:0;font-family:inherit;line-height:1.6">' + esc(beforeText) + '</pre></div>';
          }
          if (afterText) {
            panelContent += '<div style="background:#f0fdf4;border:1px solid #86efac;border-radius:6px;padding:6px 8px">' +
              '<div style="font-size:9px;font-weight:700;color:#16a34a;margin-bottom:3px"><i class="fas fa-check-circle" style="font-size:8px;margin-right:3px"></i>改稿後（例）</div>' +
              '<pre style="font-size:10.5px;color:#14532d;white-space:pre-wrap;margin:0;font-family:inherit;line-height:1.6">' + esc(afterText) + '</pre></div>';
          }
          panelContent += '</div>';
        }

        detailPanelHtml += '<div id="' + panelId + '" style="display:none;margin:4px 0 4px 36px;background:' + bgColor + ';border:1px solid ' + borderColor + ';border-radius:7px;padding:8px 12px">' +
          '<div style="font-size:10px;font-weight:700;color:' + headerColor + ';margin-bottom:5px;display:flex;align-items:center;justify-content:space-between">' +
          '<span><i class="fas ' + icon + '" style="font-size:8px;margin-right:4px"></i>' + esc(ann.label) + '</span>' +
          '<span style="font-size:9px;font-weight:400;color:#9ca3af;cursor:pointer" onclick="document.getElementById(\'' + panelId + '\').style.display=\'none\'">✕ 閉じる</span>' +
          '</div>' +
          panelContent +
          '</div>';
      });
    }

    annotHtml += '<div class="sr-ann-line2" style="' + (annotMap[ri] && annotMap[ri].some(a=>a.type==='bad') ? 'background:#fff8f8;' : annotMap[ri] && annotMap[ri].some(a=>a.type==='good') ? 'background:#f7fef7;' : '') + '">' +
      '<span class="sr-ann-lnum2">' + (ri+1) + '</span>' +
      '<span class="sr-ann-text2 ' + lineClass + '">' + lineContent + '</span>' +
      (badgeHtml ? '<div class="sr-ann-badges">' + badgeHtml + '</div>' : '') +
      '</div>' +
      detailPanelHtml;
    prevLineB = l;
  });'''

if old3 in src:
    src = src.replace(old3, new3, 1)
    patches_applied.append('3) Enhanced annotation HTML with expandable detail panels')
else:
    patches_applied.append('3) SKIP: annotation HTML block not found')

# ════════════════════════════════════════════════════════════════
# PATCH 4: CSS定義を追加（アノテーションビュー用スタイル）
# sr-ann-line2, sr-ann-badge, dialogue-line等の欠損CSS
# ════════════════════════════════════════════════════════════════
# モーダルHTMLの中にstyle blockを追加
old4 = '''  const modalEl = document.getElementById('modal-overlay');
  if (!modalEl) return;
  modalEl.innerHTML = `
    <div class="modal-dialog" style="max-width:820px;width:95vw;max-height:90vh;overflow:hidden;display:flex;flex-direction:column">
      <div class="modal-header" style="flex-shrink:0;display:flex;align-items:center;gap:10px;background:linear-gradient(135deg,#09071f,#1a0f4a);color:#fff;border-radius:12px 12px 0 0;padding:14px 18px">'''

new4 = '''  const modalEl = document.getElementById('modal-overlay');
  if (!modalEl) return;
  modalEl.innerHTML = `
    <style>
      .sr-ann-line2 { display:flex; align-items:flex-start; flex-wrap:wrap; padding:2px 8px; border-radius:3px; min-height:22px; transition:background .15s; }
      .sr-ann-line2:hover { background:#f9fafb !important; }
      .sr-ann-lnum2 { flex-shrink:0; min-width:32px; font-size:10px; color:#9ca3af; font-family:monospace; padding-top:3px; user-select:none; }
      .sr-ann-text2 { flex:1; font-size:12.5px; line-height:1.85; white-space:pre-wrap; word-break:break-all; padding-right:4px; }
      .sr-ann-badges { display:flex; flex-wrap:wrap; gap:3px; align-items:center; flex-shrink:0; padding-top:2px; padding-left:4px; }
      .sr-ann-badge { display:inline-flex; align-items:center; gap:3px; padding:1px 6px; border-radius:10px; font-size:9.5px; font-weight:600; white-space:nowrap; transition:opacity .15s; }
      .sr-ann-badge:hover { opacity:.8; }
      .sr-ann-badge.bad { background:#fee2e2; color:#b91c1c; border:1px solid #fca5a5; }
      .sr-ann-badge.warn { background:#fef3c7; color:#92400e; border:1px solid #fde68a; }
      .sr-ann-badge.good { background:#dcfce7; color:#15803d; border:1px solid #86efac; }
      .sr-ann-badge.info { background:#dbeafe; color:#1e40af; border:1px solid #93c5fd; }
      .scene-line { font-weight:700; color:#1e3a8a; background:#eff6ff; padding:1px 4px; border-radius:3px; }
      .char-line { font-weight:700; color:#7c3aed; text-align:center; display:block; }
      .dialogue-line { color:#1f2937; margin-left:16px; }
      .direction-line { color:#4b5563; font-style:italic; }
      .sr-annotated-body .scene-line { display:inline-block; }
    </style>
    <div class="modal-dialog" style="max-width:820px;width:95vw;max-height:90vh;overflow:hidden;display:flex;flex-direction:column">
      <div class="modal-header" style="flex-shrink:0;display:flex;align-items:center;gap:10px;background:linear-gradient(135deg,#09071f,#1a0f4a);color:#fff;border-radius:12px 12px 0 0;padding:14px 18px">'''

if old4 in src:
    src = src.replace(old4, new4, 1)
    patches_applied.append('4) Added CSS definitions for annotation view (sr-ann-line2, badges, line types)')
else:
    patches_applied.append('4) SKIP: modal innerHTML block not found')

# ════════════════════════════════════════════════════════════════
# PATCH 5: モーダルタイトルのアノテーション数を詳細化
# ════════════════════════════════════════════════════════════════
old5 = '''        <span style="margin-left:auto">${rawLines.length}行 · ${annotCount}件のアノテーション適用</span>'''
new5 = '''        <span style="margin-left:auto">${rawLines.length}行 · <span style="color:#ef4444;font-weight:600">${annotMap&&Object.values(annotMap).flat().filter(a=>a.type==='bad').length||0}件 要修正</span> · <span style="color:#d97706;font-weight:600">${annotMap&&Object.values(annotMap).flat().filter(a=>a.type==='warn').length||0}件 注意</span> · <span style="color:#16a34a;font-weight:600">${annotMap&&Object.values(annotMap).flat().filter(a=>a.type==='good').length||0}件 好評価</span> — 計${annotCount}件</span>'''

if old5 in src:
    src = src.replace(old5, new5, 1)
    patches_applied.append('5) Enhanced annotation count display with type breakdown')
else:
    patches_applied.append('5) SKIP: annotation count footer not found')

# ════════════════════════════════════════════════════════════════
# PATCH 6: アノテーション凡例に操作説明を追加
# ════════════════════════════════════════════════════════════════
old6 = '''            <span style="margin-left:auto;font-size:9px">バッジにカーソルを当てると詳細コメント・改稿ヒントを確認できます</span>'''
new6 = '''            <span style="margin-left:auto;font-size:9px;color:#6b7280">
              <i class="fas fa-hand-pointer" style="margin-right:3px;font-size:8px"></i>バッジをクリック → 改稿ヒント・Before/After例を展開
            </span>'''

if old6 in src:
    src = src.replace(old6, new6, 1)
    patches_applied.append('6) Updated legend text to explain click-to-expand')
else:
    patches_applied.append('6) SKIP: legend text not found')

# ════════════════════════════════════════════════════════════════
# PATCH 7: annotMap スコープをHTML生成ブロックでも参照できるよう修正
# (テンプレートリテラル内で ${annotMap} を使えるよう、変数をローカル化)
# ════════════════════════════════════════════════════════════════
old7 = '''        <span style="margin-left:auto">${rawLines.length}行 · <span style="color:#ef4444;font-weight:600">${annotMap&&Object.values(annotMap).flat().filter(a=>a.type==='bad').length||0}件 要修正</span> · <span style="color:#d97706;font-weight:600">${annotMap&&Object.values(annotMap).flat().filter(a=>a.type==='warn').length||0}件 注意</span> · <span style="color:#16a34a;font-weight:600">${annotMap&&Object.values(annotMap).flat().filter(a=>a.type==='good').length||0}件 好評価</span> — 計${annotCount}件</span>'''

# We need the annotMap stats captured BEFORE the template literal
# Insert a summary stats calculation before the modal HTML
new7_prefix = '''  // v16: Pre-compute annotation stats for template literal
  const annotBadCount = Object.values(annotMap).flat().filter(a=>a.type==='bad').length;
  const annotWarnCount = Object.values(annotMap).flat().filter(a=>a.type==='warn').length;
  const annotGoodCount = Object.values(annotMap).flat().filter(a=>a.type==='good').length;

'''

insert_before_modal = '''  const modalEl = document.getElementById('modal-overlay');'''
if insert_before_modal in src and new7_prefix not in src:
    src = src.replace(insert_before_modal, new7_prefix + insert_before_modal, 1)
    patches_applied.append('7a) Added annotation stats pre-computation')

# Now fix the template literal to use the computed variables
old7b = '${annotMap&&Object.values(annotMap).flat().filter(a=>a.type===\'bad\').length||0}件 要修正</span> · <span style="color:#d97706;font-weight:600">${annotMap&&Object.values(annotMap).flat().filter(a=>a.type===\'warn\').length||0}件 注意</span> · <span style="color:#16a34a;font-weight:600">${annotMap&&Object.values(annotMap).flat().filter(a=>a.type===\'good\').length||0}件 好評価</span>'
new7b = '${annotBadCount}件 要修正</span> · <span style="color:#d97706;font-weight:600">${annotWarnCount}件 注意</span> · <span style="color:#16a34a;font-weight:600">${annotGoodCount}件 好評価</span>'

if old7b in src:
    src = src.replace(old7b, new7b, 1)
    patches_applied.append('7b) Fixed annotation stats in template literal')
else:
    patches_applied.append('7b) SKIP: annotation stats template not found')

# ════════════════════════════════════════════════════════════════
# PATCH 8: TXTダウンロードの詳細化
# 脚本タイトル・スコア・コメントを含む詳細な診断セクション
# ════════════════════════════════════════════════════════════════
old8 = '''  out += `\\n${bar}\\n  診断ノート詳細 (${detailNotes.length}件)\\n${bar}\\n`;
  detailNotes.forEach((n,i) => {
    out += `\\n[${i+1}] ${n.type === 'bad' ? '⚠ 要修正' : n.type === 'good' ? '✓ 好評価' : 'ℹ 参考'}: ${n.label||''}\\n`;
    out += `${n.text||''}\\n`;
    if (n.quote) out += `  脚本引用: 「${n.quote.slice(0,100)}」\\n`;
    if (n.suggestion) out += `  改善提案: ${n.suggestion}\\n`;
  });'''

new8 = r'''  // v16: Enhanced diagnostic notes section with scores
  out += `\n${bar}\n  ■ 採点サマリー\n${bar}\n`;
  if (ar) {
    out += `総合スコア: ${ar.totalScore||'—'}/100点  評価: ${ar.grade||'—'} ${ar.gradeLabel||''}\n`;
    if (ar.itemScores) {
      const scoreEntries = Object.entries(ar.itemScores).sort((a,b)=>a[1]-b[1]);
      out += `\n▼ 低スコア項目（要改善）:\n`;
      scoreEntries.filter(([,v])=>v<=2).forEach(([k,v]) => {
        out += `  ${k}: ${v}/5点\n`;
      });
      out += `\n▼ 高スコア項目（強み）:\n`;
      scoreEntries.filter(([,v])=>v>=4).forEach(([k,v]) => {
        out += `  ${k}: ${v}/5点\n`;
      });
    }
    if (ar.analysisStats) {
      const st = ar.analysisStats;
      out += `\n▼ 分析統計:\n`;
      if (st.sceneCount) out += `  シーン数: ${st.sceneCount}\n`;
      if (st.uniqueChars) out += `  登場人物数: ${st.uniqueChars}\n`;
      if (st.dialogueRatio) out += `  台詞比率: ${st.dialogueRatio}%\n`;
      if (st.obstacleScoreRaw !== undefined) out += `  障壁強度: ${st.obstacleScoreRaw}/5\n`;
      if (st.tempoScoreRaw !== undefined) out += `  テンポ: ${st.tempoScoreRaw}/5\n`;
      if (st.commercialScoreRaw !== undefined) out += `  商業適合: ${st.commercialScoreRaw}/5\n`;
    }
  }
  out += `\n${bar}\n  ■ 審査員コメント\n${bar}\n`;
  if (ar && ar.judgesComments && ar.judgesComments.length > 0) {
    ar.judgesComments.forEach(j => {
      out += `\n【${j.judge}】 スコア: ${j.score}/5\n${j.comment}\n`;
    });
  } else {
    out += '（採点後に審査員コメントが生成されます）\n';
  }
  out += `\n${bar}\n  ■ 診断ノート詳細 (${detailNotes.length}件)\n${bar}\n`;
  detailNotes.forEach((n,i) => {
    out += `\n[${i+1}] ${n.type === 'bad' ? '⚠ 要修正' : n.type === 'good' ? '✓ 好評価' : 'ℹ 参考'}: ${n.label||''}\n`;
    out += `${n.text||''}\n`;
    if (n.quote) out += `  脚本引用: 「${n.quote.slice(0,100)}」\n`;
    if (n.suggestion) out += `  改善提案: ${n.suggestion}\n`;
  });'''

if old8 in src:
    src = src.replace(old8, new8, 1)
    patches_applied.append('8) Enhanced TXT download with scores, judge comments, and stats')
else:
    patches_applied.append('8) SKIP: diagnostic notes section not found')

# ════════════════════════════════════════════════════════════════
# PATCH 9: judgesComments をautoScoreResultに保存
# ════════════════════════════════════════════════════════════════
# Find the return statement of staffRoomRunAnalysis and add judgesComments to it
old9 = '''  return {
    itemScores, totalScore, grade, gradeLabel, summary,
    categoryScores, detailNotes, strengths: strengths_str, weaknesses: weaknesses_str,
    suggestions: suggestions_str, priority: priority_str,
    itemDetails, genreStr, analysisStats'''

new9 = '''  return {
    itemScores, totalScore, grade, gradeLabel, summary,
    categoryScores, detailNotes, strengths: strengths_str, weaknesses: weaknesses_str,
    suggestions: suggestions_str, priority: priority_str,
    judgesComments: judgesCommentsV13,
    itemDetails, genreStr, analysisStats'''

if old9 in src:
    src = src.replace(old9, new9, 1)
    patches_applied.append('9) Added judgesComments to return object')
else:
    patches_applied.append('9) SKIP: return statement not found')

# ════════════════════════════════════════════════════════════════
# PATCH 10: アノテーションモーダルのヘッダー「一括展開」ボタン追加
# ════════════════════════════════════════════════════════════════
old10 = '''          <button onclick="staffRoomDownloadAnnotated('${sessionId}')" style="background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.2);color:#fff;border-radius:6px;padding:5px 10px;font-size:10px;cursor:pointer;font-weight:600"><i class="fas fa-download" style="margin-right:4px"></i>TXTダウンロード</button>'''

new10 = '''          <button onclick="(function(){const ps=document.querySelectorAll('[id^=ann-panel-]');let anyHidden=Array.from(ps).some(p=>p.style.display==='none');ps.forEach(p=>p.style.display=anyHidden?'block':'none');})()" style="background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.2);color:#fff;border-radius:6px;padding:5px 10px;font-size:10px;cursor:pointer;font-weight:600" title="全コメントを一括展開/折り畳み"><i class="fas fa-expand-alt" style="margin-right:4px"></i>全展開</button>
          <button onclick="staffRoomDownloadAnnotated('${sessionId}')" style="background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.2);color:#fff;border-radius:6px;padding:5px 10px;font-size:10px;cursor:pointer;font-weight:600"><i class="fas fa-download" style="margin-right:4px"></i>TXTダウンロード</button>'''

if old10 in src:
    src = src.replace(old10, new10, 1)
    patches_applied.append('10) Added expand-all button to annotation modal header')
else:
    patches_applied.append('10) SKIP: download button not found')

# ════════════════════════════════════════════════════════════════
# PATCH 11: アノテーション要約パネルに審査員コメントを追加
# ════════════════════════════════════════════════════════════════
old11 = '''            <!-- Top issues summary -->
            ${ar && ar.detailNotes && ar.detailNotes.filter(n=>n.type==='bad').length > 0 ? `
            <div style="margin-top:8px;font-size:9.5px;color:rgba(248,113,113,.8);font-weight:600">
              <i class="fas fa-triangle-exclamation" style="font-size:8px;margin-right:3px"></i>
              最優先改稿箇所 (${ar.detailNotes.filter(n=>n.type==='bad').length}件):
              ${ar.detailNotes.filter(n=>n.type==='bad').slice(0,3).map(n=>
                `<span style="background:rgba(248,113,113,.12);border-radius:4px;padding:1px 5px;margin-left:3px">${(n.text||'').slice(0,25)}…</span>`
              ).join('')}
            </div>` : ''}
          </div>'''

new11 = '''            <!-- Top issues summary -->
            ${ar && ar.detailNotes && ar.detailNotes.filter(n=>n.type==='bad').length > 0 ? `
            <div style="margin-top:8px;font-size:9.5px;color:rgba(248,113,113,.8);font-weight:600">
              <i class="fas fa-triangle-exclamation" style="font-size:8px;margin-right:3px"></i>
              最優先改稿箇所 (${ar.detailNotes.filter(n=>n.type==='bad').length}件):
              ${ar.detailNotes.filter(n=>n.type==='bad').slice(0,3).map(n=>
                '<span style="background:rgba(248,113,113,.12);border-radius:4px;padding:1px 5px;margin-left:3px">' + (n.text||'').slice(0,25) + '…</span>'
              ).join('')}
            </div>` : ''}
            ${ar && ar.judgesComments && ar.judgesComments.length > 0 ? `
            <div style="margin-top:10px;border-top:1px solid rgba(255,255,255,.08);padding-top:8px">
              <div style="font-size:9.5px;font-weight:700;color:rgba(255,255,255,.6);margin-bottom:6px"><i class="fas fa-gavel" style="margin-right:4px;color:#c4b5fd"></i>審査員コメント (${ar.judgesComments.length}名)</div>
              <div style="display:flex;flex-direction:column;gap:5px">
                ${ar.judgesComments.slice(0,3).map(j =>
                  '<div style="background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1);border-radius:6px;padding:6px 10px">' +
                  '<div style="font-size:9px;font-weight:700;color:rgba(196,181,253,.9);margin-bottom:2px">【' + j.judge + '】 ' + j.score + '/5点</div>' +
                  '<div style="font-size:10px;color:rgba(255,255,255,.65);line-height:1.6">' + (j.comment||'').slice(0,120) + (j.comment&&j.comment.length>120?'…':'') + '</div>' +
                  '</div>'
                ).join('')}
              </div>
            </div>` : ''}
          </div>'''

if old11 in src:
    src = src.replace(old11, new11, 1)
    patches_applied.append('11) Added judges comments to annotation summary panel')
else:
    patches_applied.append('11) SKIP: top issues summary block not found')

# ════════════════════════════════════════════════════════════════
# PATCH 12: 評価軸の説明台詞検出を精密化（文脈考慮）
# clisheKwsに追加パターンを加える
# ════════════════════════════════════════════════════════════════
old12 = "  const clisheKws = ['頑張ります','よろしくお願いします','気をつけて','心配しないで','大丈夫','任せてください','信じて'];"
new12 = "  const clisheKws = ['頑張ります','よろしくお願いします','気をつけて','心配しないで','大丈夫','任せてください','信じて','絶対に諦めない','必ず帰ってくる','君のことが好きだ','俺がいる','一緒にいてくれ','お前には関係ない'];"

if old12 in src:
    src = src.replace(old12, new12, 1)
    patches_applied.append('12) Expanded cliché keyword list')
else:
    patches_applied.append('12) SKIP: clisheKws not found')

# ════════════════════════════════════════════════════════════════
# PATCH 13: シーン行の初登場人物を追跡して「登場人物紹介未設計」を検出
# (新キャラが台詞なしで登場するシーンにラベルを付ける)
# ════════════════════════════════════════════════════════════════
old13 = "  let prevLineA = '';\n  let prevPrevLineA = '';\n  let consecutiveDlgChar = '';\n  let consecutiveDlgCount = 0;"
new13 = """  let prevLineA = '';
  let prevPrevLineA = '';
  let consecutiveDlgChar = '';
  let consecutiveDlgCount = 0;
  const seenCharsA = new Set();
  let currentSceneCharCount = 0;
  let inNewScene = false;"""

if old13 in src:
    src = src.replace(old13, new13, 1)
    patches_applied.append('13) Added character tracking variables for new-char detection')
else:
    patches_applied.append('13) SKIP: tracking variables block not found')

# ════════════════════════════════════════════════════════════════
# PATCH 14: モーダルオーバーレイのdisplay問題を修正
# ════════════════════════════════════════════════════════════════
old14 = "  modalEl.style.display = 'flex';"
if old14 in src:
    # Count occurrences
    count14 = src.count(old14)
    # Only target the one in staffRoomGenerateAnnotatedScript
    # Find it in context
    ctx14 = "\n  modalEl.style.display = 'flex';\n}\n\nfunction staffRoomDownloadAnnotated"
    new14 = "\n  modalEl.style.display = 'flex';\n  modalEl.style.alignItems = 'center';\n  modalEl.style.justifyContent = 'center';\n  // Scroll to top of annotation body\n  setTimeout(()=>{const ab=modalEl.querySelector('.sr-annotated-body');if(ab)ab.parentElement.scrollTop=0;},50);\n}\n\nfunction staffRoomDownloadAnnotated"
    if ctx14 in src:
        src = src.replace(ctx14, new14, 1)
        patches_applied.append('14) Fixed modal display and added scroll-to-top')
    else:
        patches_applied.append('14) SKIP: modal display context not found')
else:
    patches_applied.append('14) SKIP: modalEl.style.display not found')

# ════════════════════════════════════════════════════════════════
# PATCH 15: v16ヘッダー表示を追加（採点結果セクション）
# ════════════════════════════════════════════════════════════════
old15 = "//  8カテゴリ・24項目・評価モード対応多軸モデル"
new15 = "//  8カテゴリ・24項目・評価モード対応多軸モデル（v16: 精密引用・展開コメント・審査員コメント保存）"

if old15 in src:
    src = src.replace(old15, new15, 1)
    patches_applied.append('15) Updated engine description comment')
else:
    patches_applied.append('15) SKIP: engine description not found')

# ════════════════════════════════════════════════════════════════
# Write output
# ════════════════════════════════════════════════════════════════
with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(src)

new_len = len(src)
print(f'Original length: {orig_len:,} chars')
print(f'New length:      {new_len:,} chars')
print(f'Delta:           {new_len - orig_len:+,} chars')
print()
print('Applied patches:')
for p in patches_applied:
    print(f'  {p}')
