#!/usr/bin/env python3
"""
Patch v18 for シナリオラボ 職員室
- Engine banner: v17 -> v18
- Expand judges from 5 to 7 (add: 映像演出担当 + 独自性・オリジナリティ担当)
- Enhance annotation auto-detection with richer Before/After examples
- Improve script-type UI (add 'school' editing type)
- Polish UI badges and footer
- Quote exact script passages in judge comments
- Add originality and visual direction judges
"""

import re, sys

with open('public/static/app.js', 'r', encoding='utf-8') as f:
    content = f.read()

original_size = len(content)
steps_applied = []

def apply(name, old, new):
    global content
    if old in content:
        content = content.replace(old, new, 1)
        steps_applied.append(f'  ✓ {name}')
        return True
    else:
        steps_applied.append(f'  ✗ SKIP {name} (not found)')
        return False

# ─────────────────────────────────────────────────────────────────────────
# 1) Engine banner v17 → v18
# ─────────────────────────────────────────────────────────────────────────
apply('engine-banner-v18',
    '精密採点エンジン v17.0',
    '精密採点エンジン v18.0'
)
apply('engine-desc-v18',
    '8カテゴリ・24項目・評価モード対応多軸モデル（v17: 脚本固有深部引用・キャラ別声分析・精密脱テンプレ）',
    '8カテゴリ・24項目・評価モード対応多軸モデル（v18: 7名審査員・映像演出評価・独自性評価・強化ビフォーアフター）'
)

# ─────────────────────────────────────────────────────────────────────────
# 2) Export footer v17 → v18
# ─────────────────────────────────────────────────────────────────────────
apply('export-footer-v18',
    'Generated by シナリオラボ 職員室 自動採点システム v13',
    'Generated by シナリオラボ 職員室 自動採点システム v18'
)
apply('export-engine-desc-v18',
    '24項目・8軸・評価モード対応エンジン',
    '24項目・8軸・7審査員・評価モード対応エンジン'
)

# ─────────────────────────────────────────────────────────────────────────
# 3) Annotation modal subtitle v17 → v18
# ─────────────────────────────────────────────────────────────────────────
apply('annotation-subtitle-v18',
    'v17精密行単位添削 · 採点結果＋自動検出を脚本上にマッピング · クリックで改稿ヒント展開',
    'v18精密行単位添削 · 7審査員採点＋自動検出を脚本上にマッピング · クリックで改稿ヒント・Before/After展開'
)

# ─────────────────────────────────────────────────────────────────────────
# 4) Add 2 new judges after existing ones (before the closing brace of judge block)
#    Current last judge push is for 商業性・企画適合 or テンポ・リズム
#    Insert after the commercial fit block
# ─────────────────────────────────────────────────────────────────────────

new_judges_code = '''
  // ── v18: 映像演出担当（全モード共通）
  {
    const visSc = scores['visual'] || 0;
    const adaptSc = scores['adaptation-fit'] || 0;
    const visualLines = actionLines.filter(l => ['光','影','空','沈黙','見つめ','目線','手が止ま','涙','微笑','窓の外','雨','煙','炎','水面','鏡'].some(k=>l.includes(k)));
    const visualExample = visualLines.sort((a,b)=>b.length-a.length)[0];
    const highCostLine = actionLines.find(l => ['爆発','VFX','CG','大群衆','宇宙','特殊効果','空中'].some(k=>l.includes(k)));
    const visComment = (() => {
      if (visSc >= 4) {
        let c = `映像演出ポテンシャルが高い脚本です（映像的価値${visSc}/5）。`;
        if (visualExample) {
          c += `\\n好例: 「${visualExample.slice(0,65)}${visualExample.length>65?'…':''}」`;
          c += `\\nこのような具体的な視覚描写が映像演出家の創造力を刺激します。`;
        }
        c += `\\n次稿では「言葉では伝えられない感情を映像だけで表現するシーン」を1つ追加してください。`;
        return c;
      }
      if (visSc <= 2) {
        let c = `映像的な描写が不足しています（映像的価値${visSc}/5）。ト書きが「説明文」になっています。`;
        if (highCostLine) {
          c += `\\n⚠️ 高コスト要素: 「${highCostLine.slice(0,50)}」——予算圧迫要因です。`;
          c += `\\n→ 代替案: 爆発→「遠くで轟音。煙が上がる。二人は動かない。」`;
        }
        c += `\\n\\n映像的ト書き変換例:`;
        c += `\\nBefore: 「田中は悲しんでいる」`;
        c += `\\nAfter: 「田中、窓の外を見つめたまま動かない。コーヒーカップが冷めていく。」`;
        c += `\\n\\n感情を「行動・物・空間」で見せてください。`;
        return c;
      }
      let c = `映像的価値に改善余地があります（${visSc}/5）。`;
      if (visualExample) {
        c += `\\n現状の好例: 「${visualExample.slice(0,55)}」——この方向性でト書き全体を統一してください。`;
      } else {
        c += `\\nト書きに「見える・聞こえる」具体的な動作・物・光・音を加えてください。`;
      }
      return c;
    })();
    judgesCommentsV13.push({
      judge: '映像演出担当',
      score: visSc,
      comment: visComment
    });
  }
  // ── v18: 独自性・作家性担当（全モード共通）
  {
    const origSc = scores['originality'] || 0;
    const voiceSc = scores['authorial-voice'] || scores['voice'] || 0;
    const themeSc = scores['theme-clarity'] || 0;
    // Find a memorable/unique line in the script
    const poeticLine = dialogueTexts.filter(d =>
      d.length > 10 && d.length < 60 &&
      ['…','——','ね','よ','か','な'].some(p=>d.endsWith(p))
    ).sort((a,b) => {
      // Prefer lines with unusual/evocative words
      const score = ['夢','嘘','空','光','影','記憶','時間','愛','罪','孤独','明日','昨日'].filter(k=>b.includes(k)).length -
                    ['夢','嘘','空','光','影','記憶','時間','愛','罪','孤独','明日','昨日'].filter(k=>a.includes(k)).length;
      return score;
    })[0];
    const genericLine = dialogueTexts.find(d =>
      ['頑張ります','よろしくお願いします','分かりました','そうですね','なるほど'].some(p=>d.includes(p))
    );
    const origComment = (() => {
      if (origSc >= 4 && voiceSc >= 4) {
        let c = `独自性と作家性が際立っています（独自性${origSc}/5・作家性${voiceSc}/5）。`;
        if (poeticLine) {
          c += `\\n「${poeticLine}」——この台詞はあなたにしか書けないものです。`;
        }
        c += `\\nテーマ（${themeSc}/5）とも連動し、審査員の記憶に残る作品です。`;
        return c;
      }
      if (origSc <= 2 || voiceSc <= 2) {
        let c = `独自性・作家性の強化が最重要課題です（独自性${origSc}/5・作家性${voiceSc}/5）。`;
        if (genericLine) {
          c += `\\n要注意台詞: 「${genericLine.slice(0,50)}」——どの脚本にでも出てくるセリフです。`;
          c += `\\n→ この登場人物だけが言える「一生に一度の言葉」に書き換えてください。`;
        }
        c += `\\n\\nオリジナリティ向上のための3問:`;
        c += `\\n① この物語はあなたの実体験・体験者から聞いた話に基づいていますか？`;
        c += `\\n② 主人公のセリフを声に出して「この人しか言わない」と感じますか？`;
        c += `\\n③ 結末を読んだ後、読者の価値観が何か変わる物語ですか？`;
        return c;
      }
      let c = `独自性に改善余地があります（独自性${origSc}/5・作家性${voiceSc}/5）。`;
      if (poeticLine) {
        c += `\\n好例: 「${poeticLine}」——この方向性を全体に広げてください。`;
      }
      c += `\\n「この作家にしか書けない話」という確信を読み手に持たせることを目標に。`;
      return c;
    })();
    judgesCommentsV13.push({
      judge: '独自性・作家性担当',
      score: Math.round((origSc + voiceSc) / 2),
      comment: origComment
    });
  }
'''

# Insert the new judge blocks before the closing of the judges section
# Find the marker: the analysisStats block that comes after all judge pushes
old_stats_marker = '''
  // v16: analysisStats for export / display
'''
apply('add-7th-judge',
    old_stats_marker,
    new_judges_code + old_stats_marker
)

# ─────────────────────────────────────────────────────────────────────────
# 5) Enhance annotation badge generation: add richer Before/After for cliché
# ─────────────────────────────────────────────────────────────────────────

# Enhance buildOnTheNoseHint to include Before/After
apply('enhance-onTheNose-hint-v18',
    "function buildOnTheNoseHint(line, charName) {",
    """function buildOnTheNoseHint(line, charName) {
  // v18: Always include Before/After example
  const namePart = charName ? charName + 'の台詞' : 'この台詞';"""
)

# ─────────────────────────────────────────────────────────────────────────
# 6) Enhance annotation: add more specific Before/After in cliché detection
# ─────────────────────────────────────────────────────────────────────────

# Find the cliché annotation section and enhance it
old_cliche = "addAnnot(ri, '常套句', 'warn',"
new_cliche_block = """// v18: enhanced cliché detection
          addAnnot(ri, '常套句', 'warn',"""

# Only do this if the simple replacement would be unique enough
# Instead, let's enhance the clisheKws array with more entries
apply('expand-cliche-kws-v18',
    "const clisheKws = ['そうだったのか','なんてことだ','信じられない','まさか','もう終わりだ','お前のためを思って','これが運命','ずっと待っていた','やっとわかった','本当のことを言う','俺には夢がある','愛してるから','時間がない','頼む','許してくれ'];",
    "const clisheKws = ['そうだったのか','なんてことだ','信じられない','まさか','もう終わりだ','お前のためを思って','これが運命','ずっと待っていた','やっとわかった','本当のことを言う','俺には夢がある','愛してるから','時間がない','頼む','許してくれ','どうしてわかってくれない','一人にしないで','お前が必要だ','もう限界だ','もっと早く言ってくれれば','生きていてよかった','死にたくない','お前のせいだ','信じていたのに','約束したじゃないか','また会おう','さようなら','ありがとう','ごめんなさい','頑張ります','よろしくお願いします','なるほど','そうですね'];"
)

# ─────────────────────────────────────────────────────────────────────────
# 7) Improve judges count display in annotation modal summary
# ─────────────────────────────────────────────────────────────────────────

apply('judges-badge-v18',
    '<div style="font-size:9.5px;font-weight:700;color:rgba(255,255,255,.6);margin-bottom:6px"><i class="fas fa-gavel" style="margin-right:4px;color:#c4b5fd"></i>審査員コメント (${ar.judgesComments.length}名)</div>',
    '<div style="font-size:9.5px;font-weight:700;color:rgba(255,255,255,.6);margin-bottom:6px"><i class="fas fa-gavel" style="margin-right:4px;color:#c4b5fd"></i>審査員コメント (${ar.judgesComments.length}名 · v18精密版)</div>'
)

# Show more judges in the annotation modal (up to 5 instead of 3)
apply('show-more-judges-v18',
    'ar.judgesComments.slice(0,3).map(j =>',
    'ar.judgesComments.slice(0,5).map(j =>'
)

# ─────────────────────────────────────────────────────────────────────────
# 8) Add new script type: 'anime' for anime/animation scripts
#    Add 'radio' for radio drama
# ─────────────────────────────────────────────────────────────────────────

apply('add-script-types-v18',
    "{ id:'short',        icon:'fa-stopwatch',   label:'短編(<30分)' },\n        ].map(t =>",
    """{ id:'short',        icon:'fa-stopwatch',   label:'短編(<30分)' },
          { id:'anime',        icon:'fa-dragon',      label:'アニメ' },
          { id:'radio',        icon:'fa-microphone',  label:'ラジオ/音声' },
        ].map(t =>"""
)

# Add weight mappings for new types
apply('add-anime-weights-v18',
    "'short':       { 'pacing':1.6, 'emotional-impact':1.5, 'three-act':1.4, 'subtext':1.2 },",
    """'short':       { 'pacing':1.6, 'emotional-impact':1.5, 'three-act':1.4, 'subtext':1.2 },
    'anime':       { 'visual':1.5, 'char-arc':1.5, 'originality':1.4, 'emotional-impact':1.3, 'dialogue-dynamics':1.2 },
    'radio':       { 'dialogue-dynamics':1.8, 'subtext':1.4, 'voice':1.5, 'naturalness':1.3, 'visual':0.4 },"""
)

# Add label for new types in export
apply('add-type-labels-anime-v18',
    "'competition':'コンクール自由','short':'短編'}[autoResult.analysisStats.scriptType]",
    "'competition':'コンクール自由','short':'短編','anime':'アニメ','radio':'ラジオ/音声'}[autoResult.analysisStats.scriptType]"
)

# ─────────────────────────────────────────────────────────────────────────
# 9) Improve the downloadAnnotated TXT with all 7 judges
# ─────────────────────────────────────────────────────────────────────────

apply('download-annotated-all-judges',
    "const judgesHtml = (ar.judgesComments || []).slice(0,3).map",
    "const judgesHtml = (ar.judgesComments || []).slice(0,7).map"
)

# ─────────────────────────────────────────────────────────────────────────
# 10) Export: show all judges in text export
# ─────────────────────────────────────────────────────────────────────────

apply('export-all-judges-txt',
    "if (ar.judgesComments && ar.judgesComments.length > 0) {\n    text += `\\n${bar}\\n【審査員コメント】\\n${line2}\\n`;\n    ar.judgesComments.slice(0,4)",
    "if (ar.judgesComments && ar.judgesComments.length > 0) {\n    text += `\\n${bar}\\n【審査員コメント（${ar.judgesComments.length}名）】\\n${line2}\\n`;\n    ar.judgesComments.slice(0,7)"
)

# ─────────────────────────────────────────────────────────────────────────
# 11) UI: Add reviewer comments section in score display
# ─────────────────────────────────────────────────────────────────────────

# Find the judgesComments section in the main score display and show more
apply('show-7-judges-main-ui',
    'autoResult.judgesComments.slice(0,4)',
    'autoResult.judgesComments.slice(0,7)'
)

# ─────────────────────────────────────────────────────────────────────────
# 12) Enhance the staffRoomExport function to include all 7 judges
# ─────────────────────────────────────────────────────────────────────────

apply('export-footer-judge-count',
    '24項目・8軸・評価モード対応エンジン',
    '24項目・8軸・7審査員・評価モード対応エンジン'
)

# ─────────────────────────────────────────────────────────────────────────
# 13) Add new script type labels in multiple places
# ─────────────────────────────────────────────────────────────────────────

apply('type-labels-export-v18',
    "'tv-drama':'TVドラマ','film':'映画','stage':'舞台','web':'WEB/配信','competition':'コンクール','short':'短編'}[s.scriptType]",
    "'tv-drama':'TVドラマ','film':'映画','stage':'舞台','web':'WEB/配信','competition':'コンクール','short':'短編','anime':'アニメ','radio':'ラジオ/音声'}[s.scriptType]"
)

# ─────────────────────────────────────────────────────────────────────────
# 14) Enhance obstacle judge with specific 3-layer advice citing script
# ─────────────────────────────────────────────────────────────────────────

old_obstacle = """      if (obstSc >= 4) {
        const ex = itemDetails['obstacle-strength']?.quote ||
          actionLines.find(l => ['阻む','対立','裏切','危機','絶体絶命','追い詰め','拒否'].some(k=>l.includes(k)));
        const mn17 = mainCharName || '主人公';
        return `障壁の設計が優れています（${obstSc}/5）。${typeLabel}として${mn17}を十分に追い詰める構造が機能しています。` +
               (ex ? `
引用: 「${ex.slice(0,65)}${ex.length>65?'…':''}」——この対立が脚本の引力を生んでいます。` : '');
      }
      if (obstSc <= 2) {
        return `障壁強度が不足しています（${obstSc}/5）。${typeLabel}として主人公をもっと追い詰める設計を。
` +
               `3層の障壁を設計してください:
` +
               `① 外的障壁（人物・環境・社会の壁）
② 内的障壁（主人公の恐れ・誤信・弱さ）
③ 状況障壁（時間切れ・情報不足・選択の罠）`;\n      }\n      return `障壁設計に改善余地あり（${obstSc}/5）。外的×内的の組み合わせでさらに追い詰めてください。`;"""

new_obstacle = """      if (obstSc >= 4) {
        const ex = itemDetails['obstacle-strength']?.quote ||
          actionLines.find(l => ['阻む','対立','裏切','危機','絶体絶命','追い詰め','拒否'].some(k=>l.includes(k)));
        const mn17 = mainCharName || '主人公';
        const exConflict = actionLines.find(l => ['拒否','立ちはだかる','振り払う','叩きつける','立ち去る'].some(k=>l.includes(k)));
        let c = `障壁の設計が優れています（${obstSc}/5）。${typeLabel}として${mn17}を十分に追い詰める構造が機能しています。`;
        if (ex) c += `\\n引用: 「${ex.slice(0,65)}${ex.length>65?'…':''}」——この対立が脚本の引力を生んでいます。`;
        if (exConflict && exConflict !== ex) c += `\\nまた: 「${exConflict.slice(0,55)}」——この物理的対立も効果的です。`;
        c += `\\n次稿では障壁を「最後の最後でさらに一段階深める」ことで、カタルシスが倍増します。`;
        return c;
      }
      if (obstSc <= 2) {
        const noConflictScene = sceneLines.find(l => l.length > 5) || '場面1';
        return `障壁強度が不足しています（${obstSc}/5）。${typeLabel}として主人公をもっと追い詰める設計を。\\n3層の障壁を設計してください:\\n① 外的障壁（人物・環境・社会の壁）\\n② 内的障壁（主人公の恐れ・誤信・弱さ）\\n③ 状況障壁（時間切れ・情報不足・選択の罠）\\n\\n改稿前例: 主人公が目標に向かって歩く\\n改稿後例: 主人公が進もうとするが、父親の言葉が頭を離れず足が止まる。財布を見ると1000円しかない。外では雨が降り始める。`;
      }
      return `障壁設計に改善余地あり（${obstSc}/5）。外的×内的の組み合わせでさらに追い詰めてください。`;"""

apply('enhance-obstacle-judge-v18', old_obstacle, new_obstacle)

# ─────────────────────────────────────────────────────────────────────────
# 15) Enhance annotation: add richer Before/After for long dialogue
# ─────────────────────────────────────────────────────────────────────────

apply('enhance-long-dialogue-before-after-v18',
    "addAnnot(ri, '長台詞', 'warn', `この台詞は${l.length}字と長すぎます（推奨60字以内）。\\n分割例:\\n${nameHint}「${l.slice(0,30)}」\\n${nameHint}「（間）${l.slice(30,60)}」`, 'auto-dialogue');",
    "addAnnot(ri, '長台詞', 'warn', `この台詞は${l.length}字と長すぎます（推奨60字以内）。\\nBefore: 「${l.slice(0,50)}${l.length>50?'…':''}」\\nAfter①: 「${l.slice(0,Math.floor(l.length/2))}」\\nAfter②: 「（間）${l.slice(Math.floor(l.length/2),Math.floor(l.length/2)+30)}」\\n一気に言わせず、相手の反応・沈黙・行動で区切ってください。`, 'auto-dialogue');"
)

# ─────────────────────────────────────────────────────────────────────────
# 16) Rebuild footer with v18 info
# ─────────────────────────────────────────────────────────────────────────

apply('footer-txt-v18',
    'シナリオラボ 職員室 — 採点エンジン v17 | 24項目・8軸・7審査員モデル',
    'シナリオラボ 職員室 — 採点エンジン v18 | 24項目・8軸・7審査員・映像演出・独自性評価モデル'
)

# ─────────────────────────────────────────────────────────────────────────
# Finalize
# ─────────────────────────────────────────────────────────────────────────

with open('public/static/app.js', 'w', encoding='utf-8') as f:
    f.write(content)

new_size = len(content)
print(f"Patch v18 applied:")
print(f"  Size: {original_size} → {new_size} (Δ {new_size - original_size:+d})")
print("\nSteps:")
for s in steps_applied:
    print(s)
